[project]
name = "pote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml-html-clean>=0.4.2",
    "requests-html>=0.10.0",
    "selenium>=4.34.0",
    "webdriver-manager>=4.0.2",
]
