[project]
name = "corey-request-toy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "lxml-html-clean>=0.4.2",
    "manim>=0.19.0",
    "requests-html>=0.10.0",
]
